### PR TITLE
AROR-1981 Remove apt dependency

### PR DESCRIPTION
**Pull request by drewblas**
apt is bundled in chef-client and throws an error now in Chef14.

### CODE REVIEW

**Comment by drewblas** [comment]
@ziggythehamster This has been tested and works, ready to be merged

**Comment by ziggythehamster** [comment]
You should make this change against upstream as our cookbook closely follows theirs. Also, ideally it remains backwards compatible. You can probably check the running Chef version in metadata.rb and selectively depend.

**Comment by drewblas** [comment]
@ziggythehamster Sure thing!  I have a couple of notes:

* metadata.rb can not have any dynamic ruby in it (no `if` statements or version constraints). It must be static.
* This removal is backwards compatible.  The apt resource was added in Chef 13, so it's no longer needed as a dependency here.  
* However in Chef14 having the package and native resource collide is a run-stopping error.  So removal is the only available option
* I can submit this change upstream for sure.  But I'd like to merge this into the active art19-patched for now so as to finish up shipping the rest of the Chef14 changes that are in line.

**Comment by ziggythehamster** [comment]
That's fine with me :)

**Pull request merged**
